"""initial migration

Revision ID: 66526e088b17
Revises: 
Create Date: 2024-09-12 00:31:53.620594

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '66526e088b17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_site')
    op.drop_table('vendas_limpa_pasta')
    op.drop_table('cliente')
    op.drop_table('services')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('credits', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('profile_pic', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='latin1_general_ci',
    mariadb_default_charset='latin1',
    mariadb_engine='InnoDB'
    )
    op.create_table('services',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('limpa_nome', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('limpa_pasta', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='services_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='latin1_general_ci',
    mariadb_default_charset='latin1',
    mariadb_engine='InnoDB'
    )
    op.create_table('cliente',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('telefone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('data_criacao', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='latin1_general_ci',
    mariadb_default_charset='latin1',
    mariadb_engine='InnoDB'
    )
    op.create_table('vendas_limpa_pasta',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('produto_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('quantidade', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('valor', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('data_venda', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='latin1_general_ci',
    mariadb_default_charset='latin1',
    mariadb_engine='InnoDB'
    )
    op.create_table('usuario_site',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('senha', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('data_criacao', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='latin1_general_ci',
    mariadb_default_charset='latin1',
    mariadb_engine='InnoDB'
    )
    # ### end Alembic commands ###
