"""empty message

Revision ID: 93122200c918
Revises: 
Create Date: 2024-09-13 15:16:41.741801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93122200c918'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('afiliado_id', sa.Integer(), nullable=True),
    sa.Column('id_encadeado', sa.String(length=255), nullable=False),
    sa.Column('indicacoes', sa.Integer(), nullable=True),
    sa.Column('vendas_fechadas', sa.Integer(), nullable=True),
    sa.Column('vendas_concluidas', sa.Integer(), nullable=True),
    sa.Column('afiliados', sa.Integer(), nullable=True),
    sa.Column('comissao_acumulada', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('data_ultima_venda', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('data_criacao', sa.Date(), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('tipo_vendedor', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['afiliado_id'], ['limpa_nome.vendedores.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['site.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='limpa_nome'
    )
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('s3_key', sa.String(length=255), nullable=False),
    sa.Column('download_link', sa.String(length=255), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('qr_code', sa.Text(), nullable=True),
    sa.Column('statusPago', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['site.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='limpa_pasta'
    )
    op.create_table('job_limpa_pasta',
    sa.Column('id_job', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('link_arquivo', sa.String(length=255), nullable=False),
    sa.Column('novo_link', sa.String(length=255), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('job_feito', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['site.user.id'], ),
    sa.PrimaryKeyConstraint('id_job'),
    schema='limpa_pasta'
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('limpa_nome', sa.Boolean(), nullable=True),
    sa.Column('limpa_pasta', sa.Boolean(), nullable=True),
    sa.Column('servico_3', sa.Boolean(), nullable=True),
    sa.Column('servico_4', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['site.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='site'
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('valor_divida', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status_pagamento', sa.String(length=50), nullable=True),
    sa.Column('status_contrato', sa.String(length=50), nullable=True),
    sa.Column('afiliado_potencial', sa.Boolean(), nullable=True),
    sa.Column('afiliado_id', sa.String(length=255), nullable=True),
    sa.Column('forma_pagamento', sa.String(length=50), nullable=True),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('data_contrato', sa.Date(), nullable=True),
    sa.Column('origem_lead', sa.String(length=100), nullable=True),
    sa.Column('documentos_recebidos', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['vendedor_id'], ['limpa_nome.vendedores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='limpa_nome'
    )
    op.create_table('comissao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('afiliado_id', sa.Integer(), nullable=False),
    sa.Column('valor_comissao', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('data_comissao', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['vendedor_id'], ['limpa_nome.vendedores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='limpa_nome'
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('payment_type', sa.String(length=50), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('correlation_id', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['limpa_pasta.file.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['site.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='limpa_pasta'
    )
    op.create_table('vendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('valor_venda', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('data_venda', sa.Date(), nullable=True),
    sa.Column('data_conclusao', sa.Date(), nullable=True),
    sa.Column('forma_pagamento', sa.String(length=50), nullable=True),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('numero_parcelas', sa.Integer(), nullable=True),
    sa.Column('valor_pago', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('data_cancelamento', sa.Date(), nullable=True),
    sa.Column('motivo_cancelamento', sa.String(length=255), nullable=True),
    sa.Column('status_pagamento', sa.String(length=50), nullable=True),
    sa.Column('tipo_venda', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['limpa_nome.clientes.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['limpa_nome.vendedores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='limpa_nome'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('vendas', schema='limpa_nome')
    op.drop_table('transaction', schema='limpa_pasta')
    op.drop_table('comissao', schema='limpa_nome')
    op.drop_table('clientes', schema='limpa_nome')
    op.drop_table('services', schema='site')
    op.drop_table('job_limpa_pasta', schema='limpa_pasta')
    op.drop_table('file', schema='limpa_pasta')
    op.drop_table('vendedores', schema='limpa_nome')
    # ### end Alembic commands ###
